/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bank.account;

public class App {

    public static void main(String[] args) {
        BankAccount newAccount = new BankAccount(1, "Bryan", "bryan@gmail.com", "01234567");
        
        newAccount.depositFunds(69.20f);
        newAccount.withdrawFunds(69.0f);
        newAccount.withdrawFunds(69.0f);

    }
}
